language: swift
os: osx
osx_image: xcode12.2
xcode_project: Latest.xcodeproj
xcode_scheme: Latest
script: xcodebuild -project Latest.xcodeproj -scheme 'Latest' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO