language: swift
os: osx
osx_image: xcode11
xcode_project: Latest.xcodeproj
install: gem install xcpretty
script: "xcodebuild -project Latest.xcodeproj -scheme 'Latest' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c && exit ${PIPESTATUS[0]}"
